### ISSUE TITLE
Skydio X2 Quadrotor following trajectory via LTV LQR

### ISSUE THREAD

**Issue by yygbruce** [lvjonok/mujoco-sysid#7]
This example cannot run and the errors:
# linearize around trajectory
A_traj = []
B_traj = []

traj_t = traj["t"]

traj_dt = model.opt.timestep

for i in range(N_DATA):
    t = i * traj_dt
    A, B = linearize(q_traj(t), v_traj(t), u_traj(t))
    A_traj.append(A)
    B_traj.append(B)

Q = np.eye(2 * model.nv)
R = np.eye(4) * 0.3

# find gains for stabilization at the end
A_stab, B_stab = linearize(
    q_data[:, -1],
    np.zeros(model.nv),
    np.ones(4) * 1.325 * 9.81 / 4,
)
# find gains for stabilization at the end
K_stab, P_stab = dlqr(A_stab, B_stab, Q, R)
K, _ = dlqr_ltv(A_traj, B_traj, Q, R)

LinAlgError                               Traceback (most recent call last)
[<ipython-input-49-de219c264cd8>](https://localhost:8080/#) in <cell line: 25>()
     23 )
     24 # find gains for stabilization at the end
---> 25 K_stab, P_stab = dlqr(A_stab, B_stab, Q, R)
     26 K, _ = dlqr_ltv(A_traj, B_traj, Q, R)

1 frames
[/usr/local/lib/python3.10/dist-packages/scipy/linalg/_solvers.py](https://localhost:8080/#) in solve_discrete_are(a, b, q, r, e, s, balanced)
    733 
    734     if norm(u_sym, 1) > sym_threshold:
--> 735         raise LinAlgError('The associated symplectic pencil has eigenvalues '
    736                           'too close to the unit circle')
    737 

LinAlgError: The associated symplectic pencil has eigenvalues too close to the unit circle

**Comment by lvjonok** [comment]
Thank you for pointing the issue. For some reason it worked a while ago :)

The problem is in matrix `R`. Please change it to `R = np.eye(4) * 0.35` and try again. I will take some time and split examples into simpler chunks and check that it works just fine a bit later.

**Comment by yygbruce** [comment]
Thanks for the great contribution!Now,It works well.

**Comment by yygbruce** [comment]
Hi, lvjonok! When the parameters are the same, which one will work better, mujoco or mujoco_sysid?

**Comment by lvjonok** [comment]
The main purpose of this repository is to provide an interface to tools used for system identification and adaptation. I do think you can use an example with a quadrotor following LTV LQR trajectory without much dependency on my repository.

**Comment by yygbruce** [comment]
Thank you, lvjnok! I have tried to use lqr to control the quadcopter many times with mujoco, but I can't achieve satisfactory results.
Maybe, you can help me.
