### ISSUE TITLE
How the  trajectories files(skydio_easy.npz and skydio.npz) is generated?

### ISSUE THREAD

**Issue by yygbruce** [lvjonok/mujoco-sysid#9]
Hi, lvjonk! How the  trajectories files(skydio_easy.npz and skydio.npz) is generated? In particular, the target 'u'?

**Comment by lvjonok** [comment]
Hello @yygbruce ! These trajectories were the result of LQR LTV for `skydio_easy` and MPC for `skydio` files. Unfortunately, I have not fixed all the scripts to reproduce them and may struggle to find them right away.

If it is critical for you, please let me know, I will try to come up with some scripts to reproduce similar trajectories.

**Comment by yygbruce** [comment]
Thank you for your reply, lvjonok!It is critical for me, looking forward to your work!

**Comment by lvjonok** [comment]
Sorry for long wait, I am back with some scripts. As I have said, `skydio_easy` is most likely to be generated using script in [notebook](https://github.com/lvjonok/mujoco-sysid/blob/master/examples/mujoco_sysid_demo.ipynb).

`skydio.npz` on the other hand, was done using MPC controller and I struggled to recover which script it was exactly, but I have found very similar: [MPC controller](https://gist.github.com/lvjonok/59472443c0bc5d2046eb296f7d80f362). The script is quite old and exact dependencies might be missing, but it can give a good starting point to recover it and apply for quadrotor control.

If you still have any questions, please let me know.

**Comment by yygbruce** [comment]
ok, thank you!
